#!/usr/bin/env bash

export codium_extensions=(
  'mads-hartmann.bash-ide-vscode'
  'timonwong.shellcheck'
  'foxundermoon.shell-format'
  'samuelcolvin.jinjahtml'
  'oderwat.indent-rainbow'
  'mechatroner.rainbow-csv'
  'mads-hartmann.bash-ide-vscode'
  'DavidAnson.vscode-markdownlint'
  'bungcip.better-toml'
  'ms-python.python'
  'ms-python.black-formatter'
  'donjayamanne.python-environment-manager'
  'reditorsupport.r'
  'redhat.vscode-yaml'
  'caponetto.vscode-diff-viewer'
  'mhutchie.git-graph'
  'usernamehw.todo-md'
  'theo-coder.the-best-theme'
  'medo64.render-crlf'
)

for extension in "${codium_extensions[@]}"; do
  codium --install-extension "$extension" --force
done
